name: packagist_network
description: Wrapper network request library for dio.
version: 1.2.4
homepage: https://github.com/flutter-packagist/network

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  dio: ^5.8.0+1
  log_wrapper: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
